services:
  app:
    image: purwantogz/php:8.4.4-phpunit
    platform: linux/amd64
    depends_on:
      - mysql
      - mailpit
      - meilisearch
      - redis
    ports:
      - "5173:5173"
    environment:
      TZ: "Asia/Jakarta"
      ENV_TYPE: "developer"
      OPCACHE_ENABLE: "FALSE"
      XDEBUG_SESSION: "smallerid-xdebug-session"
      XDEBUG_ENABLE: "true"
      XDEBUG_CLIENT_HOST: "host.docker.internal"
      XDEBUG_CLIENT_PORT: "9001"
      XDEBUG_START_REQUEST: "yes"
    volumes:
      - .:/var/www:delegated
      - /var/www/.git
      - ./storage/logs:/var/log/:delegated
      - ~/.composer/cache:/root/.composer/cache:delegated
      - ./infrastructure/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:delegated
      - ./conf_environment_docker.php:/usr/local/lib/php/conf_environment_docker.php
    dns:
      - 8.8.8.8
      - 9.9.9.9
    networks:
      - askme_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    image: purwantogz/php:8.4.4-phpunit
    platform: linux/amd64
    depends_on:
      - mysql
      - mailpit
      - meilisearch
      - redis
    environment:
      TZ: "Asia/Jakarta"
      ENV_TYPE: "developer"
      OPCACHE_ENABLE: "FALSE"
      XDEBUG_SESSION: "smallerid-xdebug-session"
    volumes:
      - .:/var/www:delegated
      - /var/www/.git
      - ./storage/logs:/var/log/:delegated
      - ~/.composer/cache:/root/.composer/cache:delegated
      - ./infrastructure/supervisord-worker.conf:/etc/supervisor/conf.d/supervisord.conf:delegated
      - ./conf_environment_docker.php:/usr/local/lib/php/conf_environment_docker.php
    dns:
      - 8.8.8.8
      - 9.9.9.9
    networks:
      - askme_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: 'mysql/mysql-server:8.0'
    platform: linux/amd64
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './infrastructure/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - askme_network

  postgres:
    image: 'postgres:17.6'
    platform: linux/amd64
    ports:
      - '${FORWARD_PGSQL_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${PGSQL_DB}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    networks:
      - askme_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    platform: linux/amd64
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${PGSQL_DB}
      KC_DB_USERNAME: ${PGSQL_USER}
      KC_DB_PASSWORD: ${PGSQL_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/askme-realm.json
    ports:
      - '${FORWARD_KEYCLOAK_PORT:-8080}:8080'
    depends_on:
      - postgres
    volumes:
      - ./infrastructure/keycloak/realm-export.json:/tmp/askme-realm.json
    networks:
      - askme_network

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    platform: linux/amd64
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    networks:
      - askme_network

  mailpit:
    image: 'axllent/mailpit:latest'
    platform: linux/amd64
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - askme_network

  web:
    build: infrastructure/nginx/
    platform: linux/amd64
    depends_on:
      - app
    ports:
      - "${FORWARD_WEB_PORT:-81}:80"
    volumes:
      - .:/var/www:delegated
      - /var/www/.git
      - ./infrastructure/nginx:/etc/nginx/conf.d:delegated
      - ./storage/logs:/var/log/:delegated
    links:
      - app
    dns:
      - 8.8.8.8
      - 9.9.9.9
    networks:
      - askme_network
    extra_hosts:
      - "host.docker.internal:host-gateway"


  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - askme_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  askme_network:
    driver: bridge
