ARG NODE_VERSION=24.7.0-alpine
FROM node:${NODE_VERSION} AS dev

WORKDIR /var/www

COPY package.json ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]